BASE_URL = "https://api.openweathermap.org/data/2.5/weather"
BASE_LANGUAGE = "en"
API_KEY = "58f6537b93cb0a4ab8022baf8019f5df"

CITIES = [
    'ljfnhsnf',
    "New York",
    "Tokyo",
    "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",
    # "New York",
    # "Tokyo",
    # "São Paulo",

]